window.READER_CONFIG = {
  appName: "Lecteur scolaire",
  appsScriptUrl: "https://script.google.com/macros/s/AKfycbzGi-A3B9SEu4-kq-K4bZmwmD5Q0x4W6moYQNxBS0sX255J89lgqgRCb90nogU9M2oV2g/exec",
  adminEmail: "tremblay.kevin@cscapitale.qc.ca",
  allowedDomainSuffixes: ["educ.cscapitale.qc.ca", "cscapitale.qc.ca"],
  githubPagesBasePath: "./assets/books",
  githubRepoOwner: "techno-cardi",
  githubRepoName: "Lecture",
  githubRepoBranch: "main",
  githubAssetsBasePath: "assets/books",
  pdfJsVersion: "5.6.205",
  autoSaveDelayMs: 500,
  publishPollDelayMs: 4000,
  maxPublishPollAttempts: 8,
  defaultReaderMode: "text",
  minPdfZoom: 0.85,
  maxPdfZoom: 2.4,
  pdfZoomStep: 0.15,
};
